name: sync_http
version: 0.1.1
author: Dart Team <misc@dartlang.org>
description: Synchronous HTTP client for Dart.
homepage: https://github.com/dart-lang/sync_http
environment:
  sdk: '>=1.24.0-dev.0.0 <2.0.0'
dev_dependencies:
  test: ">=0.12.0 <0.13.0"
